version: 2.1

orbs:
  node: circleci/node@4.0.1

parameters:
  version:
    type: string
    default: 0.4.7

general:
  branches:
    - master

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew build
      - run: ./gradlew publish

      - store_artifacts:
          path: build/libs/

      - node/install:
          install-yarn: true

      - run:
          name: Discord webhook
          command: |
            cd .circleci/discordwebhook
            yarn install
            yarn start << pipeline.git.branch >> << pipeline.parameters.version >> $CIRCLE_BUILD_NUM https://api.github.com/repos/MeteorDevelopment/meteor-client/compare/<< pipeline.git.base_revision >>...<< pipeline.git.revision >>
