name: Issue automatic actions

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  issue-moderator:
    runs-on: ubuntu-latest
    steps:
      - name: Similarity analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-threshold: 0.60
          title-excludes: ''
          comment-title: |
            ### Your issue looks similar to these issues:
            Please close if duplicate.
          comment-body: '${index}. ${similarity} #${number}'
      - uses: actions/checkout@v2
      - name: Automatically close issues that don't follow the issue template
        uses: lucasbento/auto-close-issues@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: |
            @${issue.user.login}: hello! :wave:
            This issue is being automatically closed because it does not follow the issue template." 
          closed-issues-label: "invalid"
          
